# -*- coding: utf-8 -*-
"""Number Guessing Game

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14WHOdd-fqzPD-tCgwJCashPZgE_0gVbw
"""

import random

print("\n🎮 NUMBER GUESSING GAME 🎮")
print("--------------------------")

name = input("Enter player name: ")
print(f"Welcome {name} 😎")

print("\nChoose Level:")
print("1. Easy")
print("2. Moderate")
print("3. Hard")

level = input("Enter choice (1/2/3): ")

# Level settings + rewards
if level == "1":
    level_name = "Easy"
    low, high = 1, 100
    attempts = 10
    reward = 100
elif level == "2":
    level_name = "Moderate"
    low, high = 1, 150
    attempts = 5
    reward = 500
elif level == "3":
    level_name = "Hard"
    low, high = 1, 200
    attempts = 3
    reward = 1000
else:
    print("Invalid choice ❌")
    exit()

secret = random.randint(low, high)

print(f"\n🔥 Level: {level_name}")
print(f"Range: {low} - {high}")
print(f"Attempts: {attempts}\n")

# Game loop
for i in range(1, attempts + 1):
    guess = int(input(f"Attempt {i}/{attempts}: "))
    diff = abs(secret - guess)

    if guess == secret:
        print("\n🎉 YOU WIN 🎉")
        print(f"Nice one {name}! 😎")
        print(f"🪙 You earned {reward} coins!")
        print("🏆 Level Cleared!")
        break

    # Distance hint (every attempt)
    if diff > 40:
        print("Out of zone ❌")
    elif diff > 15:
        print("Almost there 👀")
    else:
        print("So close 🔥")

    # Direction hint (every attempt)
    if guess < secret:
        print("⬆️ Go higher\n")
    else:
        print("⬇️ Go lower\n")

else:
    print("\n💀 GAME OVER")
    print(f"Correct number was: {secret}")
    print("No coins this time 😅")